services:
  # Service Backend (API Flask)
  backend:
    image: ${DOCKERHUB_USERNAME:-dimitricalmand}/news-summary-backend:latest
    container_name: news-summary-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - FLASK_ENV=production
    volumes:
      # Persistance des données pour les articles
      - ./data:/app/data
    networks:
      - news-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Limitation des ressources pour Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Service Frontend (React/Vite)
  frontend:
    image: ${DOCKERHUB_USERNAME:-dimitricalmand}/news-summary-frontend:latest
    container_name: news-summary-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - news-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Limitation des ressources pour Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

# Réseau bridge personnalisé
networks:
  news-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes pour la persistance des données
volumes:
  articles_data:
    driver: local